import type { Metadata } from "next";
import { jose } from "@/fonts/fonts";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${jose.variable}`}>
      <body className="font-joseSans bg-veryLightGray_light">{children}</body>
    </html>
  );
}
